.travis.yml
README.md
build.xml

This PR includes:
- an ant `build.xml` file with a `compile` task
- a `travis.yml` file to install dependencies, and call that task
- a README for the repo, which includes a travis badge
**HAS BEEN TESTED ON ROBORIO**
@widakay @c0d3rman 
-aj

Setup Travis to compile standard repo

---

commands/healthchecks/AbstractHealthCheck.java

This pull request:
- removes the implicit "diamond interface syntax" typing
- allows misconfigured travis to build
**TESTED ON ROBORIO**

Remove diamond interface to make travis happy

---

LogKitten.java

The level-log methods without overrides had a different call hierarchy level, which broke the stack-trace usage.

Fixed call hierarchy in logkitten.

---

custom/sensors/CANInfraredDistanceSensor.java
custom/sensors/CANUltrasonicDistanceSensor.java
custom/sensors/DistanceSensor.java

This PR:
- adds `DistanceSensor` interface
- adds `CANInfraredDistanceSensor` class (subclass of CANSensor)

add distance sensor framework

---

LogKitten.java

LogKitten exception logging now has override as a parameter, rather than overriding by default.

Fixed LogKitten exception override

---

subsystems/motor/speedmodifiers/IdentityModifier.java

For one thing, super(1) is parsed as an implicit integer cast to double, which is very slow (at least one cpu instruction).
Also, multiplying the speed by 1.0D each time a motor is set is inefficient (hundreds of extra CPU instructions per second)

Identity Modifier should not multiply each value by 1

---

custom/sensors/CANInfraredDistanceSensor.java
custom/sensors/CANUltrasonicDistanceSensor.java
custom/sensors/DistanceSensor.java

Corrected a bug in standard where DistanceSensor's `getDistance` and `getDistanceSafely` have the opposite meanings to the corresponding methods in PIDSensor

Flipped getDistance and getDistanceSafely

---

LogKitten.java

> No one needs to call LEVEL_DEBUG.compare(LEVEL_LOG,LEBEL_VERBOSE); all that's needed is LEVEL_DEBUG.compareTo(LEVEL_LOG), which is comparable.

kittenlevel doesn't need to implement comparator, only comparable

---

LogKitten.java

instead of passing redundant information in the constructor, just use the name of the enum

Logkitten better enums

---

LogKitten.java

Yes that would require a new function signature for every primitive. However, thanks to Java autoboxing int -> Integer and such, you can pass an int literal to a function that expects an Object. So, LogKitten.wtf(5) will work already for example. @c0d3rman

replaced every instanceof string with object in logkitten

---

custom/CustomCAN.java
custom/CustomNeoPixels.java
custom/sensors/CANEncoder.java
custom/sensors/CANInfraredDistanceSensor.java
custom/sensors/CANSensor.java
custom/sensors/CANUltrasonicDistanceSensor.java

This is to fix an ongoing issue with CAN reading and implement a better sensor management system upon that being fixed.
According to typical CAN system designs, sensors should be pushing data constantly. Previously, we were using a call and response system.
There was previously an error where, due to incorrectly initialized CAN ids on the Teensy side, most messages were being lost. In addition, the mask on the RoboRIO side had an error that was leading to further message loss, although this was introduced more recently.
The RoboRIO masking issues are fixed here, and the previous measures taken to allow some communication were eliminated. Sensors no longer attempt to write before reading either.

Fix CAN Read Issue

---

LogKitten.java

While `logLevel`, `dsLevel`, and `printLevel` are modified, `DEFAULT_LOG_LEVEL` and co aren't

These are never modified therefore can be final

---

LogKitten.java

implements Comparable is implied because it's an enum

unnecesary implements

---

commands/healthchecks/HealthLevel.java

All enums implement `Comparable` anyway, so it's unnecessary to be explicit about it.

enum implements

---

commands/motor/MotorSet.java
custom/motioncontrollers/BangBangController.java
subsystems/motor/Motor.java
subsystems/motor/speedmodifiers/AccelerationCap.java

Adding a `double` to a `String` converts the `double` to a `String` anyway, so `Double.toString()` is unnecessary.

string append converts double to string anyway

---

custom/CommandSendableChooser.java

Instead of extending `SendableChooser` it should extend `SendableChooser<Command>`. This fixes all eclipse warnings.

more generics

---

custom/motioncontrollers/CustomPIDController.java

Added minNominalOutput to CustomPIDController.
added setMinNominalOutput() to CustomPIDController, sets the minNominalOutput.
added getMinNominalOutput() to CustomPIDController, gets the minNominalOutput.
Edited get() so that if |result| is less than the minNominalOutput than it puts it to minNominalOutput or -minNominalOutput depending on if it's above or below 0.

added minimum nominal output functionality to custom pid controller

---

subsystems/motor/Motor.java

When logging the speed to which a motor was set, don't log the calling method.
Issue #144

Remove call stack traversal from motor.set() log

---

custom/sensors/PDP.java

The PowerDistributionPanel class throws exceptions that can not be caught (based on tests by @c0d3rman). In order to get around this, the DriverStation voltage can be read, but this potentially has latency and does not include amperage data.
This pull request basically reads the CAN data directly, which allows us to control the exceptions.

PDP class reading CAN directly

---

commands/RunUntil.java
commands/RunWhile.java
commands/WaitUntil.java
commands/WaitWhile.java

Added convenience commands using Boolean Suppliers to run something/wait while/until something is true. Could be used in `2017-Code`'s `Shoot`.

Added convenience Until/While commands

---

commands/SingleOp.java

`SingleOp` used to be an abstract class, and to use it, one would make an anonymous subclass of it. That was nasty and the syntax of an anonymous class forced line breaks into a lot of places and made them ugly (like `bindCommands()` in 2017-Code's `NathanGain`). Let's use lambdas (implemented through `Runnable`).

Use Runnable in SingleOp

---

subsystems/chassis/Chassis.java

Make sure that the double[] motorSpeeds is initialized in the constructor so it can be retrieved without error before the first chassis command is run.

set a default value for chassis motor speeds

---

custom/sensors/CANEncoder.java

It appears that when the entire robot is active, RoboRIO CAN send is unreliable. This deals with that by sending encoder resets many times. If anyone has time to develop a better solution, that would be good.

Made reset on encoders resistant to RoboRIO send error

---

commands/chassis/ChassisTurn.java

Fixed `ChassisTurn`'s first tick issue. The fix mirrors `ChassisMoveDistance`.

Fix ChassisTurn's first tick issue

---

custom/CustomCAN.java

Added exception handling so that the CAN bus being cut doesn't kill the bot.
The stacktrace printing logic should eventually be moved to LogKitten.

Added exception handling to CustomCAN

---

custom/sensors/PDP.java

Should not have actually had an throw there, now just ignoring until timeout.

Fixed PDP printing errors when none actually exist

---

subsystems/motor/speedmodifiers/AccelerationCap.java

When the PDP was disconnected, it used to fallback to using voltage read from the DriverStation. This seems to have been suboptimal (still trying to figure out why). Now it simply falls back to a very basic version of ramping.

AccelerationCap no longer uses PDP DriverStation voltage fallback

---

custom/TypedNamedSendableChooser.java

If typednademsendablechooser implemented supplier, then you could have a pretty elegant way of, for example, having the driver station set a desired dead reckoning speed. Where your Supplier<Double>, passed into the PIDController, is just the TypedNamedSendableChooser<Double>

TypedNamedSendableChooser implements Supplier<T>

---

custom/motioncontrollers/CANTalonSRX.java

By using this we can ensure that in the likely event of a breaking update where they don't implement SpeedController, we can easily fix it without changing it in yearly code.

Added vanity TalonSRX wrapper

---

.travis.yml
build.xml

No longer use t4904.xyz domain to host files required for building.

Remove references to externally hosted files from travis

---

custom/sensors/CANSensor.java

When we updated to the new CANJNI method signatures, some faulty logic was introduced. More specifically, `ByteBuffer`s filled using the #put() method were not rewound like they were when they came directly from CANJNI.

fix bad CAN logic

---

Util.java

This is a direct response to #209 regarding Double.MIN_VALUE being used in Util.isZero().
**Summary**
A commonly used heuristic to determine whether or not a float is zero is to use the ULP of a double.  This is defined as the distance between the given double value and the double value next largest in magnitude. By taking the square root, we get a commonly used heuristic for determining whether or not a double is small enough to be considered zero. (Note that Java calculates this value to be approximately `1.4901161193847656E-8`.)
We restructure Util.isZero() to accept the following inputs:
- `Util.isZero(double var, double epsilon)` _Checks if `Math.abs(var) < epsilon`_
- `Util.isZero(double var)` _Calls the above method with `epsilon = Math.sqrt(Math.ulp(1.0))`_
This should not require …

Fix Util.isZero() zero detection using ULP heuristic

---

commands/GuardCommand.java

Apparently this was replaced so I just marked it as deprecated, as suggested by Nikhil.

2020 update gaurd command
