RoboticsTeam4904/standard

commands/chassis/ChassisIdle.java, commands/chassis/ChassisMove.java, commands/motor/ControlMotor.java, commands/motor/MotorIdle.java, commands/motor/MotorSet.java, subsystems/chassis/Chassis.java, subsystems/chassis/TankDrive.java, subsystems/motor/AccelMotor.java, subsystems/motor/EncodedMotor.java, subsystems/motor/MotorGroup.java
Acceleration limiting works, is safe (for the gearboxes), and is tested.
=> Accellimit

custom/CustomCAN.java, custom/sensors/CANEncoder.java, custom/sensors/CANSensor.java, custom/sensors/CustomButton.java, custom/sensors/CustomDigitalEncoder.java, custom/sensors/CustomDigitalLimitSwitch.java
This is the version that worked with the ultrasonic sensor. It should be possible to read data from any sensor that transmits with the first four bytes (in the Teensy array) being an int. It may support multiple modes. This has not been tested.
=> Can sensors

commands/TimedCommand.java, commands/chassis/ChassisShift.java, commands/healthchecks/AbstractHealthcheck.java, commands/healthchecks/HealthProtectCommand.java, commands/healthchecks/HealthStatus.java, commands/healthchecks/InterruptCompressor.java, commands/healthchecks/PressureReleaseValve.java
This provides the compressor valve open health check.
=> Healthchecks

.travis.yml, LogKitten.java, commands/TimedCommand.java, commands/chassis/ChassisIdle.java, commands/chassis/ChassisMove.java, commands/healthchecks/AbstractHealthCheck.java, commands/motor/ControlMotor.java, commands/motor/MotorIdle.java, commands/motor/MotorSet.java, subsystems/motor/AccelMotor.java
This PR adds the `LogKitten` class in to the `standard` library.
**HAS BEEN TESTED ON ROBORIO**
@c0d3rman @carterturn 
-aj
=> merge in LogKitten

custom/controllers/XboxController.java
Updated to commit 9c81297 of XboxController.
Backwards-compatible (added 2 methods.)
=> Updated XboxController.java

commands/chassis/ChassisMove.java, commands/chassis/ChassisSet.java, custom/ChassisController.java, humaninterface/Driver.java
This improves the structure of the chassis move system.
=> Chassismove

subsystems/motor/MotorFactory.java
This makes making motors easier.
=> Motor factory

subsystems/motor/MotorFactory.java
Added default inverted to MotorFactory.getAccelMotorGroup
=> Motor factory update

LogKitten.java
This PR:
- aliases the current log file to a common file
- includes the calling class in log messages
=> LogKitten Updates

custom/sensors/CANTalonEncoder.java, custom/sensors/TalonEncoder.java
Basically just reading the encoder over the talon.
=> CANTalon encoder

custom/sensors/CANEncoder.java
This removes rateMode boolean, people should use PIDSourceType instead.
CustomPID makes this reasonable.
=> Removed obsolete rateMode boolean.

custom/PIDChassisController.java
Setup PID to only fire while driving.
=> Pid chassis controller

LogKitten.java
This PR:
- doesn't log the class's entire package in LogKitten
=> don't log the entire package in LogKitten

commands/SafetyCommand.java
This PR:
- adds Command's constructors to SafetyCommand
I don't think it needs to be tested, due to the nature of the changes.
=> SafetyCommand constructors

custom/sensors/CANTalonEncoder.java
Removed rateMode from CANTalonEncoder and added convenience constructors.
=> CANTalonEncoder remove rateMode

custom/controllers/CustomXbox.java
=> CustomXbox axes

CommandRobotBase.java
This improves the CommandRobotBase to look more like a Command and reduce the ability of mistakes to impede critical robot functionality.
=> Commandrobotbase rewrite

commands/Noop.java, commands/RunIf.java, commands/RunIfElse.java, commands/RunUnless.java
Tested all cases with 2 commands - acts like an AND gate
=> Made RunIfElse take multiple BooleanSuppliers

commands/SingleOp.java
=> Single Op!

LogKitten.java
Added exception logging capabilities to LogKitten.
(Tested on Pinkie.)
=> Added exception logging

CommandRobotBase.java
Fixed the lack of `autonomousCommand` starting in `autonomousInit` and improved some comments and whitespace.
This makes the current `skynet` branch of `standard` branch obsolete.
=> CommandRobotBase Autonomous Fix

LogKitten.java
This PR synchronizes all of the LogKitten logging methods.
This mirrors the changes on `skynet-sockets`.
@HowardStark please devise a way to test this and report back.
=> Synchronized logkitten logging methods

commands/chassis/ChassisIdle.java, commands/chassis/ChassisMove.java, custom/controllers/Controller.java, subsystems/chassis/Chassis.java, subsystems/chassis/MecanumChassis.java, subsystems/chassis/SwerveChassis.java, subsystems/chassis/TankDrive.java
Improved Chassis and surrounding classes. Removed obsolete methods, refactored, added and improved comments, and made ChassisMove stop scaling (in favor of doing it in individual Drivers.)
=> Chassis fix

CommandRobotBase.java
add CommandRobotBase#alwaysExecute()
=> add CommandRobotBase#alwaysExecute()

commands/motor/MotorControl.java
This replaces the inversion boolean with a scaling double.
=> Control motor scale

commands/GuardCommand.java
This PR adds `GuardCommand`, which allow any indefinite command to be run in parallel with but restricted to the duration of another, set-time command.
=> add GuardCommand (useful for AUTO routines)

custom/motioncontrollers/CustomPIDController.java
This made GoalAlign immediately stop on the first tick after a reset.
=> Made CustomPIDController not onTarget right after reset

custom/motioncontrollers/CustomPIDController.java, subsystems/motor/SensorMotor.java
I think this could work. It does not seem to make things worse.
=> Tim twitch

CommandRobotBase.java
Adds a function that cleans up all teleop, autonomous, and healthcheck commands when any new state is initialized.
=> CommandRobotBase cleanup

.travis.yml, LogKitten.java, custom/CustomCAN.java, custom/sensors/CANTalonEncoder.java, subsystems/motor/Motor.java
- driver station printing in LogKitten has been updated to use new FRC Networking logic
- CANJNI has been updated to use new FRC Networking naming
- remove CANJaguar
Note: I apologize for the formatting updates. However, the current state they are in is in accordance with the Eclipse formatting profile.
=> Update standard lib for 2017 WPILib changes

LogKitten.java
Appending strings *inside* a StringBuilder.append, and then appending strings *to the output of the StringBulider*.
=> stringbuilder antipatterns

custom/TypedNamedSendableChooser.java
like the other generic pull, this one fixes all the eclipse warnings for the file, etc
=> fixed generics in typednamedsendablechooser

commands/RunIfElse.java
reduces code duplication by using `this(` syntax to call the other constructor
=> use this constructor syntax

commands/RunAll.java
i am amazed by all the inventive ways to concatenate strings in the standard library. in this case, we shouldn't create a new string array for no reason. (String.join uses the same StringJoiner internally, so this can only help not hurt)
=> better string joining

CommandRobotBase.java, LogKitten.java, Util.java, commands/chassis/ChassisMoveDistance.java, commands/chassis/ChassisTurn.java, commands/chassis/ChassisTurnAbsolute.java, commands/motor/MotorPositionConstant.java, custom/CustomCAN.java, custom/motioncontrollers/CustomPIDController.java, custom/motioncontrollers/MotionController.java, custom/sensors/CANEncoder.java, custom/sensors/CANInfraredDistanceSensor.java, custom/sensors/CANTalonEncoder.java, custom/sensors/CANUltrasonicDistanceSensor.java, custom/sensors/CustomDigitalEncoder.java, custom/sensors/CustomEncoder.java, custom/sensors/EncoderGroup.java, custom/sensors/InvalidSensorException.java, custom/sensors/PIDSensor.java
Uses new changes up to RoboticsTeam4904/4904matter#3cf6dec7e87322b85e8648c15a0e4010cc5e06d1.
=> Update formatting standard

Util.java, custom/motioncontrollers/BangBangController.java, custom/motioncontrollers/MotionController.java
Replace epsilon with double min value
=> remove epsilon

subsystems/motor/ServoSubsystem.java
Added a Subsystem that handles servos to the standard library.
=> Added ServoSubsystem

custom/sensors/CANSensor.java
Readded CAN ID to CANSensor error message.
Nobody names their CANSensors, so this helps determine which node is having issues.
=> Better CAN logging

custom/sensors/CANEncoder.java
Added a constructor for just a name and an ID (could be used in `2017-Code`'s `RobotMap`).
=> Added another CANEncoder constructor

commands/motor/MotorPositionConstant.java
Added null check for fallbackCommand to MotorPositionConstant.
=> Added null check

commands/motor/speedmodifiers/SetEnableableModifier.java, subsystems/motor/speedmodifiers/EnableableModifier.java
Improve enable-able modifier and move it to `standard` from `2017-Code`.
=> Add EnableableModifier to standard

custom/controllers/TeensyController.java
made teensy controller with 30 custombuttons
=> Teensy joystick

commands/motor/speedmodifiers/SetEnableableModifier.java
This PR allows SetEnableableModifier to operate on multiple EnableableModifiers.
=> setEnableableModifier to take in many modifiers

custom/controllers/TeensyController.java
=> changed teensyController indexes

LogKitten.java
Now uses Exception’s implementation of writing to an output.
=> Changed LogKitten.ex implementation

subsystems/motor/speedmodifiers/AccelerationCap.java
Removed some now uneeded code from AccelerationCap
=> Cleaned up acceleration cap

custom/motioncontrollers/CustomPIDController.java, custom/motioncontrollers/MotionController.java
I term was growing too large, D term was probably acting up as well.
=> Dealing with first tick issues in CustomPIDController

commands/ThresholdCommand.java
I Took the threshold command and added it to standard. Will run the command when it gets past a certain point. Once merged, we should add to 2017-Code.
=> Threshold Command

commands/chassis/ChassisMoveDistance.java, custom/motioncontrollers/MotionController.java
This deals with some enable/disable/reset issues and first tick issues.
=> Cleaned up ChassisMoveDistance

custom/motioncontrollers/CustomPIDController.java
Allow the `I` term to have a maximum threshold.
=> Improved PID's use of the I constant.

subsystems/chassis/SolenoidShifters.java
This should make toggle shifting work and report correct shift-state values.
=> Fixed internal tracking of shift state

LogKitten.java
this buffers the output stream. the buffer makes it so it doesn't do a file system write immediately each time, it builds them up and writes perhaps dozens of lines at a time.
=> BufferedOutputStream

.travis.yml, custom/CustomCAN.java, custom/sensors/CANSensor.java, custom/sensors/CANTalonEncoder.java, subsystems/motor/Motor.java
Fix the things that the new WPILib release has broken. Some changes in commmon with ave4224's similar commit:
https://github.com/c0d3rman/standard/commit/35be23869291cbd3d1d79106c5e673bb2ff2af73
=> update for 2018 wpilib release and new CTRE libs

commands/motor/MotorControlAccelCap.java
Not currently in 2018-competition for some reason, fixing this.
=> Added MotorControlAccelCap

LogKitten.java, commands/chassis/ChassisMove.java, commands/chassis/ChassisTurnAbsolute.java, commands/motor/MotorConstant.java, commands/motor/MotorPositionConstant.java, custom/motioncontrollers/CustomPIDController.java, subsystems/chassis/TankDrive.java
Started by adding derivative thresholding for pid, then added more fixes. Most up to date version for 2018 robot
=> Comp with d stop

CommandRobotBase.java, LogKitten.java, commands/chassis/ChassisMove.java, commands/chassis/ChassisTurnAbsolute.java, commands/motor/MotorConstant.java, commands/motor/MotorControlAccelCap.java, commands/motor/MotorPositionConstant.java, custom/CustomCAN.java, custom/PCMPort.java, custom/motioncontrollers/CustomPIDController.java, custom/sensors/CANEncoder.java, custom/sensors/CANSensor.java, custom/sensors/NavX.java, subsystems/chassis/TankDrive.java, subsystems/chassis/TankDriveShifting.java
=> 2018 competition

.travis.yml, CommandRobotBase.java, LogKitten.java, Util.java, custom/CustomCAN.java, custom/motioncontrollers/CustomPIDController.java, custom/motioncontrollers/MotionController.java
changed paths of several imports to match WPILib 2019
=> changed paths of several imports to match WPILib 2019

custom/motioncontrollers/CustomPIDController.java
Accumulate the value of the `Kp*p+Ki*i+Kd*D` expression over time, as the approximate integral of the PID output, and allow it to added to the output with the I' coefficient.
=> PID Output Integrals

custom/CustomCAN.java, custom/sensors/PDP.java
Adds a readSafely method to CustomCAN.
=> Add readSafely method to CustomCAN

custom/controllers/XboxController.java
Fixed #120 with suggested formula. The results for side-to-side comparisons between the old and new formulas can be found at https://repl.it/repls/SuburbanSameDehardwarization.
=> Rewrite getEnum() rounding for accuracy

commands/ThresholdCommand.java
Except for only ½ of them because I'm not actually doing `TimedCommand.java`.
=> fixed ThresholdCommand to use CommandBase

commands/WaitUntil.java, commands/WaitWhile.java
WaitUntil and WaitWhile fixed to use CommandBase.
=> Update wait commands

Util.java
Fix docblocks, formatting based on suggestions in #235.
=> Update docblocks and formatting from #235

commands/chassis/SimpleSplines.java, subsystems/chassis/SensorDrive.java
Implemented WPILib Ramsete Splines with custom spline commands and drive wrapper subsystems.
=> Simple splines

commands/Cancel.java
Fixed `standard/commands/Cancel.java`
=> Cancel updates

commands/InjectedCommand.java, commands/InjectedCommandGroup.java
InjectedCommandGroup is implemented sketchily because we don't have a `CustomCommandGroup`
=> 2020 update injected command

commands/SafetyCommand.java, commands/SingleOp.java, commands/SpawnCommand.java
Fixed `SafteyCommand.java`, `SingleOp.java`, `SpawnCommand.java` to use `CommandBase`.
=> Commands that start with s

custom/sensors/CustomCANCoder.java
Custom version of CTRE CANCoder so it can be used for PID as a CustomEncoder
=> Custom can coder

commands/chassis/SimpleSplines.java, subsystems/chassis/SensorDrive.java, subsystems/chassis/SplinesDrive.java
Added layers to the Drive classes such that non-spline implementations of a sensor-leveraging drive base would be feasible.
=> Splines drive

CommandRobotBase.java, commands/chassis/SimpleSplines.java, commands/motor/MotorSet.java, custom/PCMPort.java, custom/motioncontrollers/CANTalonFX.java, custom/motioncontrollers/CANTalonSRX.java, custom/motioncontrollers/ContinuousServoController.java, custom/sensors/CANTalonEncoder.java, custom/sensors/CustomDigitalEncoder.java, subsystems/chassis/SensorDrive.java, subsystems/chassis/SplinesDrive.java, subsystems/motor/Motor.java, subsystems/motor/PositionSensorMotor.java, subsystems/motor/SensorMotor.java, subsystems/motor/VelocitySensorMotor.java
=> Update for 2022

udp/Client.java, udp/Server.java, udp/UDPTest.java, udp/tests/TestUDPServer.java, udp/tests/UDPTest.java
A standard UDP implementation using the Java implementation of MessagePack. Usage examples can be found in the test folder.
=> Standard UDP implmentation using MessagePack
